// src/components/Navbar/Navbar.svelte
<script lang="ts">
  import { NAV_LINKS } from "$data";
  import { page } from "$app/stores";
</script>

<nav class="fixed top-6 left-1/2 -translate-x-1/2 leading-6 z-50">
  <div
    class="flex rounded-full bg-white/90 px-3 text-sm font-medium text-zinc-800 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur leading-6"
  >
    {#each NAV_LINKS as link}
      <a
        class={`${
          link.path === $page.url.pathname
            ? "text-indigo-500"
            : "text-zinc-800 hover:text-indigo-500"
        } relative block px-3 py-2`}
        href={link.path}
      >
        {link.label}

        {#if link.path === $page.url.pathname}
          <span
            class="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 to-teal-500/0 via-indigo-400"
          />
        {/if}
      </a>
    {/each}
  </div>
</nav>

// src/components/navbar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { NAV_LINKS } from "~/data";

export function Navbar() {
	const pathname = usePathname();

	return (
		<nav className="fixed top-6 left-1/2 -translate-x-1/2 leading-6 z-50">
			<ul className="flex rounded-full bg-white/90 px-3 text-sm font-medium text-zinc-800 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur leading-6">
				{NAV_LINKS.map((link) => (
					<li key={link.path}>
						<Link
							className={`${
								link.path === pathname
									? "text-indigo-500"
									: "text-zinc-800 hover:text-indigo-500"
							} relative block px-3 py-2`}
							href={link.path}
						>
							{link.label}
							{link.path === pathname && (
								<span className="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 to-teal-500/0 via-indigo-400" />
							)}
						</Link>
					</li>
				))}
			</ul>
		</nav>
	);
}
